In [1]:
# Greedy-style Procedure. 
# Program reads an external data file.  

import sys
import numpy as np
import pandas as pd
import math
import random
import time
from scipy.optimize import linear_sum_assignment

start_time = time.time()

num_list = []

def load_data(file_name):
    a = np.loadtxt(file_name)
    a = list(a)
    a = [int(i) for i in a]

    b = len(a)
    n = math.pow(b, 1./3.)
    if type(n) != "int":
        n = math.ceil(n)

    for x in a:
        x = int(x)
        num_list.append(x)

    factory =[]
    m = n*n
    for j in range(n):
        lb=j*m
        ub=(j+1)*m 
        factory = factory + num_list[lb:ub]

    factories = [factory[j:j+m] for j in range(0, len(factory), m)]
    return (a, factories)
 

# Update the path to load your date=a sample
data_file = r"C:/Users/mehbalim/Desktop/Temp Sep 2021/B&S_3IAP_n4_instance1.txt"

(a, factories) = load_data(data_file)
n = len(factories)

assign = {'Jobs':[],'Machines':[],'Factories':[],'Cost':[]}
df = pd.DataFrame(assign)
df = df.astype('int64', copy=False)
df["Cost"] = df['Cost'].astype('float')

tables = factories

#print()
print("The 3-Index Assignment Problem is of size", n, ", i.e.", n, "jobs for", n, "machines, in", n, "factories. \n")

def select_One_minimum(matrix, k, option = 0):
    """
    This function selects one min candidate from a list of candidates, i.e. tie-case.
    Set option to select either random tie-case, or firt tie-case or the last.
    For random option = 1, for first or last option = 0 or -1 respectively.
    """

    row_ind, col_ind = linear_sum_assignment(matrix)
    cost_list = matrix[(row_ind, col_ind)]

    minlyst=[]
    for i in range(k):
        if cost_list[i] == min(cost_list):
            minlyst.append([row_ind[i], col_ind[i]])

    min_indices = [i for i in range(k) if cost_list[i] == min(cost_list)]
    ## random 
    if option == 1: 
        mi = len(min_indices)
        
        t=(random.randint(0,mi-1))  
        row_ix=min_indices[t]
        
    # first or last (i.e. 0 or -1)     
    else:      
        row_ix=min_indices[option]
        
    cost_value=min(cost_list)
    
    row_indx = -1
    col_indx = -1
    for j in range(n):
        if j==row_ix:
            
            row_indx=row_ind[j]
            col_indx=col_ind[j]
            break  
    
    return (cost_value, row_indx, col_indx)

def two_matrices(mat):
    fact0=mat[0]
    fact1=mat[1]
    lst=[]

    for i in range(4):
        v=fact0[i]+fact1[3-i]
        lst.append(v)
        
    opt_cost = min(lst) 
    
    ix=lst.index(opt_cost)
    
    cost0=fact0[ix] 
    cost1=fact1[3-ix]
                           
    if ix==0:
        indx=0
        jndx=0
    
    elif ix==1:
        indx=0
        jndx=1

    elif ix==2:
        indx=1
        jndx=0
 
    else:
        indx=1
        jndx=1
    kndx=n-2  
     
    assign0={'Jobs':indx, 'Machines':jndx,'Factories':kndx,'Cost':cost0}
    assign1={'Jobs':1-indx, 'Machines':1-jndx,'Factories':kndx+1,'Cost':cost1}
    
    return(assign0, assign1, opt_cost)

k = n
factnb=-1
Total = 0.00
while k!=2:
    newT = []
    i = 0

    for t in tables:
        if i == 0:
            arr=np.asarray(t).reshape(k,k)
            arr = np.array(arr)
            print(arr, '\n')
            (cost_value, row_indx, col_indx) = select_One_minimum(arr, k, option = 1)
            factnb=factnb+1
            
            assign={'Jobs':row_indx, 'Machines':col_indx,'Factories':factnb,'Cost':cost_value}
            df=df.append(assign, ignore_index=True)
            df = df.astype('int64', copy=False)
            Total=Total + cost_value
            
            new_table=[]
            ix=row_indx
            iy=col_indx
        else:
            arr=np.asarray(t).reshape(k,k)
            print(arr, '\n')
            row_idx = ix
            col_idx = iy
            new_mat = np.delete(arr, row_idx, 0)
            new_mat = np.delete(new_mat, col_idx, 1)
            print(new_mat,'\n')
            new_mat = np.array(new_mat).flatten().tolist()
            newT.append(new_mat)
        i=i+1
    k=k-1
    tables=newT
    
(assign0, assign1, opt_cost) = two_matrices(tables)
Total=Total + opt_cost
df=df.append(assign0, ignore_index=True)
df=df.append(assign1, ignore_index=True)
df = df.astype('int64', copy=False)
      
#print(df,'\n')

print("Total cost = ", "%.2f" % Total,'\n')

print("--- %.8f seconds ---" % (time.time() - start_time))


The 3-Index Assignment Problem is of size 4 , i.e. 4 jobs for 4 machines, in 4 factories. 

[[51 17 30 53]
 [94 17 70 22]
 [49 12  8 38]
 [27 36 98 53]] 

[[76 64 76 78]
 [82 15 62 31]
 [34 91 51 40]
 [60 78 93 86]] 

[[76 64 78]
 [82 15 31]
 [60 78 86]] 

[[86 67 75 58]
 [38 35 20 82]
 [41 46 97 12]
 [21 95 73 40]] 

[[86 67 58]
 [38 35 82]
 [21 95 40]] 

[[78 75 95  2]
 [31 75 24 58]
 [ 4 95 31  5]
 [44 91 57 11]] 

[[78 75  2]
 [31 75 58]
 [44 91 11]] 

[[76 64 78]
 [82 15 31]
 [60 78 86]] 

[[86 67 58]
 [38 35 82]
 [21 95 40]] 

[[86 58]
 [21 40]] 

[[78 75  2]
 [31 75 58]
 [44 91 11]] 

[[78  2]
 [44 11]] 

Total cost =  46.00 

--- 0.01580358 seconds ---
