In [43]:
import numpy as np

import math
import random

from scipy.optimize import linear_sum_assignment

global arr, tables, Total, factnb

In [44]:
# Make sure the number of values in your text file is a squared number (e.g. 25, 36, 81, 100 etc)
# Also, the file should have one entry per line.
# This file has an example of 121 entries, the user is free to change the values and the size of the file.

file_name = r"C:\Users\mehbalim\Desktop\sample_data_for_hungarian_method.txt"

a = np.loadtxt(file_name)
a = list(a)
a = [int(i) for i in a]

b = len(a)
n = math.pow(b, 1./2.)

if type(n) != "int":
    n = math.ceil(n)
    
num_list = []

for x in a:
    x = int(x)
    num_list.append(x)

In [45]:
# Simple Hungarian Method for 2D Assignment problem.
# Reading an internal data list of size n^2 data.


factory =[]
m = n*n
for j in range(n):
    lb=j*m
    ub=(j+1)*m 
    factory = factory + num_list[lb:ub]

factories = [factory[j:j+m] for j in range(0, len(factory), m)]
    
global arr, tables, Total, factnb

tables = factories

def select_One_minimum(matrix):

    row_ind, col_ind = linear_sum_assignment(matrix)
    cost_list = matrix[(row_ind, col_ind)]

    print("Hungarian method solution for this matrix is:") 
    print(cost_list)

    minlyst=[]
    for i in range(k):
        minlyst.append([row_ind[i], col_ind[i]])
    print("Positions in the data matrix:")
    print(minlyst, '\n')
    print("Total cost =", matrix[row_ind, col_ind].sum())
    
k=n
factnb=-1
newT = []
#print(a, '\n')

arr=np.asarray(a).reshape(k,k)
arr = np.array(arr)
print("This is the input data matrix:")
print(arr, '\n')
select_One_minimum(arr)
#factnb=factnb+1       
#new_table=[]


This is the input data matrix:
[[27  1  3 51 72 30  6 15 71 28 42]
 [29 83 24 53 90 55  2 18 64 23 45]
 [31 90 39 45 40 60 40 48 18 88  5]
 [23 42 76 80 13 96 69 30 19 22 47]
 [24 46 91 39 55 14 28 11 13 33 95]
 [21 63  1 85 11 45 67 21 20 31  7]
 [41 87 46 22 68 39 73 80 96 65 60]
 [18 75 34 76 77 76 22 45 98 30 29]
 [36 64 63 95 78 38 46 87 79 63 79]
 [46 41 55 92 73 35  5 25 24  2 82]
 [31 37 65 90  9 82 51 32 16 79 53]] 

Hungarian method solution for this matrix is:
[ 1  2  5 19 11  1 22 18 38  2  9]
Index values in the data matrix:
[[0, 1], [1, 6], [2, 10], [3, 8], [4, 7], [5, 2], [6, 3], [7, 0], [8, 5], [9, 9], [10, 4]] 

Total cost = 128
